# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68cabeb0000d9094cfed25832b4bae36dc522311e278212e4ef63ab8ff6f230a56c274619404967c70f1943ab1b50ffcc6222ae221150f89d69579900b936d21

test:
  secret_key_base: 0980c88a727c5410ad2a98245712af075c7bbb774169f43f4dcd411887a4b3de2ba095097905545f554c3e94eb4090d4ebe8b227f3946e1554ab00492ea77379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
